language: ruby
rvm:
  - "2.4.0"
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - "rake db:test:prepare"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
